export const meals = [
  {
    title: 'BreakFast',
    time: '08:00 AM',
    items: ['Idli', 'Dosa', 'Pongal', 'Vada / Egg', 'Coffee / Tea'],
  },
  {
    title: 'Lunch',
    time: '01:00 PM',
    items: [
      'Steamed Rice',
      'Sambar',
      'Rasam',
      'Poriyal',
      'Vada / Egg',
      'Curd',
      'Papad',
    ],
  },
  {
    title: 'Dinner',
    time: '09:00 PM',
    items: ['Chapati', 'Kurma', 'Mixed Rice', 'Raita'],
  },
];

export const orphanageData = {
  message: 'Orphanage Information fetched Successfully',
  success: true,
  data: [
    {
      orphanageId: 1,
      name: 'abc Thunai',
      founderName1: 'Wilson Jabaraj',
      founderName2: 'Mohamad Asiu',
      founderName1Thoughts:
        'As the founder, my deepest belief is that every child, no matter their circumstances, deserves a loving home, a bright future, and the opportunity to thrive.',
      founderName2Thoughts:
        'My vision is to create a sanctuary where every child feels valued, supported, and empowered to reach their fullest potential.',
      aboutUs:
        'Welcome to Ganesh Thunai, a place where love, hope, and care come together to nurture and support children in need. Our mission is to provide a safe, loving, and supportive environment for orphaned, abandoned, and vulnerable children, helping them grow into confident, well-rounded individuals who can lead successful and meaningful lives.',
      mission:
        'At Ganesh Thunai, we are dedicated to offering more than just basic care; we focus on the holistic development of each child. Our mission is to provide:\n\n- Safety and Security: A safe, nurturing environment where children can feel protected and cared for.\n\n- Love and Emotional Support: Every child deserves to feel loved and valued. Our dedicated staff offer emotional support and build strong, caring relationships with the children.\n\n- Education and Learning: We believe in the power of education to transform lives.',
      vision:
        'We envision a world where no child has to face life’s challenges alone, where every orphaned or abandoned child has the chance to grow up with the love and support they deserve, and where their future is filled with hope, opportunities, and success.',
      programs:
        'Residential Care, Education Support, After-School Activities, Health & Wellbeing, and Vocational Training & Mentorship',
      regNo: '456ss456456',
      regDate: '2000-11-16',
      mobileNo: '8888888888',
      type: 'OLDAGE_CARE',
      website: 'www.GaneshThunai-helpus.com',
      emailId: 'Ganeshthunai.helpus@gmail.com',
      twitterId: '@Ganeshthunai-helpUs',
      instaId: '@AGaneshthunai-helpUs',
      facebookId: '@Ganeshhunai-helpUs',
      strength: 500,
      total_emp: 0,
      address: {
        addressLine1: 'New no. 14 / old no. 27 pilayar kovil Street',
        addressLine2: 'Kodambakkam',
        addressLine3: 'near kali bari temple',
        city: 'Chennai',
        state: 'TamilNadu',
        pincode: '600024',
      },
      rangePincodes: ['600024', '600033'],
      mealAmountPerDay: 6000,
      mealMenu: null,
      bookedDays: 0,
      bookingYear: 2024,
      createdDate: null,
      modifiedDate: null,
    },
  ],
};

export const allCountry = [
  'Afghanistan',
  'Albania',
  'Algeria',
  'Andorra',
  'Angola',
  'Antigua and Barbuda',
  'Argentina',
  'Armenia',
  'Australia',
  'Austria',
  'Azerbaijan',
  'Bahamas',
  'Bahrain',
  'Bangladesh',
  'Barbados',
  'Belarus',
  'Belgium',
  'Belize',
  'Benin',
  'Bhutan',
  'Bolivia',
  'Bosnia and Herzegovina',
  'Botswana',
  'Brazil',
  'Brunei',
  'Bulgaria',
  'Burkina Faso',
  'Burundi',
  'Côte dIvoire',
  'Cabo Verde',
  'Cambodia',
  'Cameroon',
  'Canada',
  'Central African Republic',
  'Chad',
  'Chile',
  'China',
  'Colombia',
  'Comoros',
  'Congo (Republic of the)',
  'Costa Rica',
  'Croatia',
  'Cuba',
  'Cyprus',
  'Czech Republic',
  'Democratic Peoples Republic of Korea(North Korea)',
  'Democratic Republic of the Congo',
  'Denmark',
  'Djibouti',
  'Dominica',
  'Dominican Republic',
  'Ecuador',
  'Egypt',
  'El Salvador',
  'Equatorial Guinea',
  'Eritrea',
  'Estonia',
  'Eswatini',
  'Ethiopia',
  'Fiji',
  'Finland',
  'France',
  'Gabon',
  'Gambia',
  'Georgia',
  'Germany',
  'Ghana',
  'Greece',
  'Grenada',
  'Guatemala',
  'Guinea',
  'Guinea-Bissau',
  'Guyana',
  'Haiti',
  'Honduras',
  'Hungary',
  'Iceland',
  'India',
  'Indonesia',
  'Iran',
  'Iraq',
  'Ireland',
  'Israel',
  'Italy',
  'Jamaica',
  'Japan',
  'Jordan',
  'Kazakhstan',
  'Kenya',
  'Kiribati',
  'Kuwait',
  'Kyrgyzstan',
  'Lao Peoples Democratic Republic(Laos)',
  'Latvia',
  'Lebanon',
  'Lesotho',
  'Liberia',
  'Libya',
  'Liechtenstein',
  'Lithuania',
  'Luxembourg',
  'Madagascar',
  'Malawi',
  'Malaysia',
  'Maldives',
  'Mali',
  'Malta',
  'Marshall Islands',
  'Mauritania',
  'Mauritius',
  'Mexico',
  'Micronesia (Federated States of)',
  'Monaco',
  'Mongolia',
  'Montenegro',
  'Morocco',
  'Mozambique',
  'Myanmar',
  'Namibia',
  'Nauru',
  'Nepal',
  'Netherlands',
  'New Zealand',
  'Nicaragua',
  'Niger',
  'Nigeria',
  'North Macedonia',
  'Norway',
  'Oman',
  'Pakistan',
  'Palau',
  'Panama',
  'Papua New Guinea',
  'Paraguay',
  'Peru',
  'Philippines',
  'Poland',
  'Portugal',
  'Qatar',
  'Republic of Korea (South Korea)',
  'Republic of Moldova (Moldova)',
  'Romania',
  'Russian Federation (Russia)',
  'Rwanda',
  'Saint Kitts and Nevis',
  'Saint Lucia',
  'Saint Vincent and the Grenadines',
  'Samoa',
  'San Marino',
  'Sao Tome and Principe',
  'Saudi Arabia',
  'Senegal',
  'Serbia',
  'Seychelles',
  'Sierra Leone',
  'Singapore',
  'Slovakia',
  'Slovenia',
  'Solomon Islands',
  'Somalia',
  'South Africa',
  'South Sudan',
  'Spain',
  'Sri Lanka',
  'Sudan',
  'Suriname',
  'Sweden',
  'Switzerland',
  'Syrian Arab Republic (Syria)',
  'Tajikistan',
  'Thailand',
  'Timor-Leste',
  'Togo',
  'Tonga',
  'Trinidad and Tobago',
  'Tunisia',
  'Turkey',
  'Turkmenistan',
  'Tuvalu',
  'Uganda',
  'Ukraine',
  'United Arab Emirates',
  'United Kingdom',
  'United Republic of Tanzania',
  'United States of America',
  'Uruguay',
  'Uzbekistan',
  'Vanuatu',
  'Venezuela',
  'Viet Nam',
  'Yemen',
  'Zambia',
  'Zimbabwe',
  'Holy See (Vatican City)',
  'State of Palestine'
]

